
name: 'Build react app'

description: 'Build a react app with specified paths'

input:
  node-version:
    description: Selected node version
    
runs:
  using: "composite"
  steps:
    - name: Setup node 
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
    - name: Test
      shell: bash
      run: |
        ls -la
        node -v
        npm -v
