
name: 'Build react app'

description: 'Build a react app with specified paths'

input:
  node-version:
    description: Selected node version
  project-path:
    description: Path to React project ('package.json')
  docker-registry-url:
    description: Url to save Docker images
  docker-username:
    description: Username to login
  docker-pat:
    description: Auth token from secrets
  docker-image-url:
    description: Url to push image to (with version tag like :latest)
    
runs:
  using: "composite"
  steps:
    - name: Setup node 
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.project-path }}
        ls -lah
        npm i
        npm run build

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry-url }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-pat }}

    - name: Build Docker Image
      shell: bash
      env:
        DOCKER_GITHUB_REGISTRY_URL: ${{ inputs.docker-image-url }}
        DOCKER_GITHUB_ACCESS_TOKEN: ${{ inputs.docker-pat }}
        DOCKER_GITHUB_USERNAME: ${{ inputs.docker-username }}
      run: |
        ls -lah
        echo "Docker buildx"
        docker buildx build --platform linux/arm64 --tag $DOCKER_GITHUB_REGISTRY_URL -f cicd/Dockerfile .
        echo "Docker push"
        docker push $DOCKER_GITHUB_REGISTRY_URL
        docker logout

    - name: Test
      shell: bash
      run: |
        ls -la
        node -v
        npm -v
