
name: 'Build target Docker file and Push to docker registry'

description: 'Build a react app with specified paths and build and push it into the given registry'

input:
  docker-filename:
    description: Filename of target Dockerfile to be executed
    default: Dockerfile

  docker-registry-url:
    description: Url to save Docker images
    required: true

  docker-username:
    description: Username to login
    required: true

  docker-pat:
    description: Auth token from secrets
    required: true

  docker-image-url:
    description: Url to push image to (with version tag like :latest)
    required: true

  docker-arch-platform:
    description: Platform architecture where the image is executed (For more see the official Docker webpage)
    default: 'linux/arm'
    
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry-url }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-pat }}

    - name: Build Docker Image
      shell: bash # TODO: could be shell? why?
      env:
        DOCKER_GITHUB_ACCESS_TOKEN: ${{ inputs.docker-pat }}
        DOCKER_GITHUB_USERNAME: ${{ inputs.docker-username }}
      run: |
        echo "ls -lah"
        ls -lah
        echo "docker buildx build --platform ${{ inputs.docker-arch-platform }} --tag ${{ inputs.docker-image-url }} -f cicd/${{ inputs.docker-filename }} ."
        docker buildx build --platform ${{ inputs.docker-arch-platform }} --tag ${{ inputs.docker-image-url }} -f cicd/${{ inputs.docker-filename }} .
        echo "docker push ${{ inputs.docker-image-url }}"
        docker push ${{ inputs.docker-image-url }}
        echo "docker logout"
        docker logout

