
name: 'Build target Docker file and Push to docker registry'

description: 'Build a react app with specified paths and build and push it into the given registry'

input:
  docker-registry-url:
    description: Url to save Docker images
    required: true

  docker-username:
    description: Username to login
    required: true

  docker-pat:
    description: Auth token from secrets
    required: true
    
  docker-image-url:
    description: Url to push image to (with version tag like :latest)
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry-url }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-pat }}

    - name: Build Docker Image
      shell: bash # TODO: could be shell? why?
      env:
        DOCKER_GITHUB_IMAGE_URL: ${{ inputs.docker-image-url }}
        DOCKER_GITHUB_ACCESS_TOKEN: ${{ inputs.docker-pat }}
        DOCKER_GITHUB_USERNAME: ${{ inputs.docker-username }}
      run: |
        ls -lah
        echo "Docker buildx"
        docker buildx build --platform linux/arm64 --tag ${{ inputs.docker-image-url }} -f cicd/Dockerfile .
        echo "Docker push"
        docker push ${{ inputs.docker-image-url }}
        docker logout

