name: Build nupkg from .NET library project

description: Create a .NET release build output

# TODOS:
# - set version
# - show important information inside cli

inputs:
  dotnet-version:
    description: Target build output dotnet version
    required: true

  dotnet-output-dir:
    description: Output directory of published files
    default: "./out"

  dotnet-target-framework:
    description: Target framework to build against
    required: true

  dotnet-target-runtime:
    description: Target runtime to run the app on
    required: true

  project-name:
    description: Target project file to execute
    required: true

  project-path:
    description: Path from root / to folder where project-name lives
    required: true

  params:
    description: Additional params

runs:
  using: "composite"
  steps:
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
